### ISSUE TITLE
Column positions mod section?

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#10]
I would try experimenting with that. The 6 I know of:
LDUR: No flip, no invert
RUDL: Flip
DLRU: Invert
URLD: Flip, -100% invert
LUDR: 25% flip, -75% invert
RDUL: 75% flip, 75% invert

These will all work on 4 panel single mode.
3 panel, invert doesn't display correctly, the right and down columns overlap...
6 panel (solo): The first 4 work correctly but I don't know about the other 2
Double: First 4 work correctly, but the other 2 could move/shift the panels over for some weird and confusing effects

In pump, the first 3 work correctly. Invert puts the center panel on the left and (I think) it goes: upright-downleft-downright-upleft. IDK what the other 3 will do...

Also, if I can find out every possible reverse/split/alternate/cross combination, that could be done too.
And do you really have to be 18 or older to play Consensual? I am only 16...

**Comment by kyzentun** [comment]
I don't know what you're trying to suggest here.

The "Must be 18 or older" part is a joke on the name of the theme.

**Comment by 1033Forest** [comment]
What I'm trying to suggest: A new modifier section, which lists flip/invert combinations to change up the positions of the columns.

**Comment by kyzentun** [comment]
I'm not limited to just what can be done with flip and invert.  The modifier system in 5.1 will let me put columns wherever I want.  Same goes for the noteskin positioning the columns.

**Comment by 1033Forest** [comment]
Hmm nice. So that means combinations not possible with invert and flip can be done, like DULR or something. 24 possible combinations in single (4 * 3 * 2 * 1 = 24). 720 in solo, 6 in 3 panel, and 40320 in techno/double. In pump, there would be 120.

**Comment by kyzentun** [comment]
There are already too many obscure rarely used options to justify more that wouldn't even be used.

**Comment by 1033Forest** [comment]
Another thing I like experimenting with: Determining which columns scroll up or down (like if one column scrolls down while the other 3 scroll up, or vice versa). But it shouldn't take a whole bunch of guesswork to determine how many % of reverse, split, alternate, or cross to use.

**Comment by kyzentun** [comment]
Mock up a menu system that allows setting up/down for each column and reordering them in a simple way and I'll implement it.

**Comment by 1033Forest** [comment]
A menu, where it shows the columns that will be used in that game type, can be selected to be up or down by selecting it, by pressing enter to change it. For example the menu could look like this:

<--
Left: UP
Down: UP
Up: UP
Right: UP

and say you want the left arrow down, press enter while left is highlighted then:
Left: DOWN
Down: UP
Up: UP
Right: UP

**Comment by 1033Forest** [comment]
A better summary of how the menus work

A better menu system I thought of for the column reversal section:
In there, all the columns for that specific game type will be listed. To toggle a column up or down, have it highlighted, then press enter. There will also be an option to reset the columns (back to all up), or reverse the selections (with this changes up to down and vice versa). This way, modifiers that are supposed to reverse only one column won't break in other game modes.

The column position section:
Lets you switch up the columns. All the columns for that specific game type are listed and each one will be given a number. For example: left = 1, down = 2, up = 3, and right = 4. To change the position of a column, change the number by highlighting the column you want to change, then select what position (number) you want the column at. Like if you want flip, left = 4, down = 3, up = 2, right = 1. If 2 or more columns have the same number they will overlap at that column position.

For other experimental stuff (like random noteskins and random note colors) that goes under the Special section.
