### ISSUE TITLE
Consensual not working

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#12]
I got a message that says "The master branch of Consensual only supports StepMania 5.1.-3 and newer". I am using something newer than 5.1.-3, I am using 5.1.-2 (5.1 alpha 2). After I press enter it redirects back to the default theme. How do I fix this?

**Comment by kyzentun** [comment]
-3 is newer than -2.  It goes by the absolute value of the number, so that non-stable releases don't bump into some upper limit.

Until there is another stepmania release, you have to be using the most recent checkout from the 5_1_0 branch of stepmania.

**Comment by 1033Forest** [comment]
Oops... I thought -2 was bigger than -3...

**Comment by 1033Forest** [comment]
I can't find 5.1.-3. Where is it? Even searching for it I can't find it...

**Comment by kyzentun** [comment]
> Until there is another stepmania release, you have to be using the most recent checkout from the 5_1_0 branch of stepmania.
