### ISSUE TITLE
Certain songs crash in the editor (no matter if tabbing or not)

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#13]
Went through the editor very fast (with tab) and it crashed.

StepMania5.1.0 crash report (build 6cc70b3, 20160401 @ 22:38:38)
--------------------------------------

Crash reason: Unhandled Microsoft C++ Exception

Thread: Main thread
        GraphicsWindow.cpp:55 Msg 256, wParam 00000009, lParam 400f0001
        GraphicsWindow.cpp:55 Msg 256, wParam 00000028, lParam 01500001
        Screen.cpp:167 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:167 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:167 ScreenMessage(SM_UpdateTextInfo)
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:778 
        InputHandler_DirectInput.cpp:754 
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:778 
        InputHandler_DirectInput.cpp:754 
Thread: Streaming sound buffering
75a8c54f: KERNELBASE!RaiseException [75a80000+c4f7+58]
75a8c54f: KERNELBASE!RaiseException [75a80000+c4f7+58]
017cc338: StepMania!012c0000
01848189: StepMania!012c0000
017cf30c: StepMania!012c0000
017ce0ef: StepMania!012c0000
017ce2ad: StepMania!012c0000
017cef30: StepMania!012c0000
017cee39: StepMania!012c0000
77d5e40c: ntdll!RtlInitUnicodeString [77d30000+2e2a8+164]
77d5e40c: ntdll!RtlInitUnicodeString [77d30000+2e2a8+164]
77d5e172: ntdll!RtlAllocateHeap [77d30000+2e0c6+ac]
01372494: StepMania!012c0000
0184b5ce: StepMania!012c0000
0184b5ce: StepMania!012c0000
013b6174: StepMania!012c0000
77d5e0a3: ntdll!RtlFreeHeap [77d30000+2e025+7e]
757a14bd: kernel32!HeapFree [75790000+114a9+14]
018624a0: StepMania!012c0000
01845437: StepMania!012c0000
01841559: StepMania!012c0000
01834991: StepMania!012c0000
0142a57b: StepMania!012c0000
018624a0: StepMania!012c0000
77d5e0a3: ntdll!RtlFreeHeap [77d30000+2e025+7e]
757a14bd: kernel32!HeapFree [75790000+114a9+14]
018624a0: StepMania!012c0000
01586c6d: StepMania!012c0000
0151bd08: StepMania!012c0000
014a1fc4: StepMania!012c0000
0142a4d6: StepMania!012c0000
0142ae4d: StepMania!012c0000
01436f5f: StepMania!012c0000
01712aa5: StepMania!012c0000
0142ae4d: StepMania!012c0000
0165b757: StepMania!012c0000
013f83fc: StepMania!012c0000
01371b42: StepMania!012c0000
0137b5f0: StepMania!012c0000
01862f17: StepMania!012c0000
01862f07: StepMania!012c0000
01862f07: StepMania!012c0000
017816d6: StepMania!012c0000
01846777: StepMania!012c0000
77d698d5: ntdll!RtlInitializeExceptionChain [77d30000+3989f+36]

Static log:
StepMania5.1.0
Compiled 20160401 @ 22:38:38 (build 6cc70b3)
Log starting 2016-06-10 14:32:26
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 4060mb total, 4095mb swap (2503mb swap avail)
Video driver: Intel(R) G45/G43 Express Chipset [Intel Corporation]
              8.15.10.1840, 7-3-2009 [pci\ven_8086&dev_2e22]
WARNING: RegOpenKeyEx(%p,%s) error (The system cannot find the file specified.)
Sound device 0: Speakers (High Definition Audio, 0.0, MID 1, PID 65535 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
WARNING: Video renderer list has been changed from 'd3d,opengl' to 'opengl'
Video renderers: 'opengl'
Mode: ICD 32 (888) 8 alpha 16 depth 64 accum 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: Intel
OGL Renderer: Intel(R) G45/G43 Express Chipset
OGL Version: 2.1.0 - Build 8.15.10.1840
OGL Max texture size: 4096
OGL Texture units: 8
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_3DFX_texture_compression_FXT1
  GL_ARB: color_buffer_float, depth_texture, draw_buffers, fragment_program, fragment_shader, half_float_pixel, 
    multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, shader_objects, 
    shading_language_100, shadow, texture_border_clamp, texture_compression, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_non_power_of_two, 
    texture_rectangle, transpose_matrix, vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI_separate_stencil
  GL_EXT: abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, blend_subtract, 
    clip_volume_hint, compiled_vertex_array, draw_range_elements, fog_coord, framebuffer_object, 
    multi_draw_arrays, packed_pixels, rescale_normal, secondary_color, separate_specular_color, shadow_funcs, 
    stencil_two_side, stencil_wrap, texture3D, texture_compression_s3tc, texture_env_add, texture_env_combine, 
    texture_filter_anisotropic, texture_lod_bias, texture_rectangle, texture_sRGB, texture_swizzle
  GL_IBM_texture_mirrored_repeat
  GL_NV: blend_square, conditional_render, texgen_reflection
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
  GL_WIN_swap_hint
OpenGL Windowed 854x480 16 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 3 (buffered)
WARNING: Startup time: 6.1510000228882
Players joined: P1
Lost focus to: StepMania.exe, chrome.exe
Top Screen: ScreenEdit
Language: en
Current renderer: OpenGL
Theme: consensual-master

Partial log:
01:02.456: RageSound: Load "/Themes/_fallback/Sounds/GameplayAssist clap.ogg" (precache: 1)
01:02.459: RageSound: Load "/Themes/_fallback/Sounds/GameplayAssist clap.ogg" (precache: 1)
01:02.460: RageSound: Load "/Themes/_fallback/Sounds/GameplayAssist clap.ogg" (precache: 1)
01:02.583: Starting thread: Streaming sound buffering
01:02.583: Loaded "ScreenEdit" ("ScreenEdit") in 0.646000
01:02.583: PushScreen: "ScreenEdit"
01:02.584: RageSound: Load "/Themes/_fallback/Sounds/_missing.ogg" (precache: 0)
01:02.584: Approximate sound time: driver frame 2746575, m_pImpl->m_Queue frame 0..9216 (dist 13519), closest position is 9216
01:02.585: Zeroing this update.  Was 2.664000
01:03.141: 19 FPS, 19 av FPS, 8317 VPF, OpenGL

-- End of report

**Comment by kyzentun** [comment]
Can you describe what you were doing in more detail?  I tried hold tab and down (to scroll downwards), and stepmania didn't crash.

**Comment by 1033Forest** [comment]
I was holding tab to get to the edit screen really fast then I tabbed down and then crash. This happened on some ITG 2 songs. It only seems to happen with some songs and not others.

Songs I tested: Robotix, Sweet World, Sunshine (ITG 2, all crashed)
Agent Blatant (ITG 2, OK)
Anubis (ITG 2, OK)

**Comment by kyzentun** [comment]
Must be something weird in those simfiles.  Upload them.

**Comment by 1033Forest** [comment]
http://www.mediafire.com/download/xcrc2l7d08858i5

**Comment by 1033Forest** [comment]
This happens even in the default theme. I should've put this under stepmania issues, instead of this theme issues, but that's OK

**Comment by kyzentun** [comment]
Blame wolfman for not checking the format strings when changing the string formatting library.
Fixed: https://github.com/stepmania/stepmania/commit/e4969053f21ef53163a4e6a66fe909cc2eb90c56

**Comment by 1033Forest** [comment]
Another thing I've been wondering: In the newfield, why do the receptors shake when playing in the editor? I am using the default noteskin

**Comment by kyzentun** [comment]
Should be fixed by this commit: https://github.com/stepmania/stepmania/commit/6e598003fc530990137dd20c90c136be00ce3cdf

**Comment by 1033Forest** [comment]
Tried another ITG 2 song (Vertex^2) (version before this commit is the one I am still using) and it crashed after I got to measure 5.

**Comment by 1033Forest** [comment]
Move this to stepmania issue #1155.
