### ISSUE TITLE
Pro timing and other old modifiers, and new experimental stuff with the newfield/newskins

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#14]
Can the old modifiers from 5.0 work on 5.1 with the new modifier system? If they are able to work, a new section under "Effects" should be added (Field Modifiers).

Also, can pro timing return? This time, there can be 2 kinds: simple (just shows a number, like 3.9), or extended (shows the number, %, and bar telling if you stepped early or late, like 5.0). The number can be positive or negative (negative means stepped early, positive means late). 0 means it was stepped on the exact frame of the receptor, not even one millisecond off.

Halve noteskin should be another modifier too. I've seen "halved" noteskins before, which halves the note colors so it looks as if the chart was playing at double the BPM (example: if 4th=red, 8th=blue, 16th=yellow, and 32nd=orange, then with halved noteskin on, 4th=red, 8th=red, 16th=blue, 32nd=yellow). 12ths would not be affected (doubling the BPM on 12ths would then be 6ths, the same color as 12ths), but 24ths would be 12ths, and 48ths would be 24ths. 192nds wouldn't be affected either. This saves time and can halve any noteskin so there is no need to edit graphics to make your own halved note/metal/delta/whatever noteskin. Got this idea from FFR where in the settings menu there is the option to halve the noteskin. 

Column colors is also a good idea too (saves time for players having to make their own column-colored noteskins). This works on note colored noteskins: specify whichever color you want a certain column to be (for example: if you want blue-red-red-blue, then left=8th, down=4th, up=4th, and right=8th). Since different noteskins can have different colors, that's why it shows the number names instead of color names (4th, 8th, 12th, ... instead of red, blue, purple, ...). Got this idea from FFR and KBO.

There could also be the option to make every note a single color (Flat; got the idea from KBO), or randomize the note colors (got that idea from a Pulsen screenshot that I saw once). These options (Halve noteskin, column colors, single colors, random color) are only available if selected a rhythm-colored noteskin.

As I said before, this theme is like an all-purpose "test theme", so that's why I post experimental modifier requests here.

**Comment by kyzentun** [comment]
Turn on the error bar if you want something like pro timing.  I didn't stick a number in it because a number seems too distracting.

**Comment by 1033Forest** [comment]
Another idea: Will the other scroll mods come back? That's what I requested a while ago and thought of the menu system for. 

Example: If you want Split: (press enter while a column is highlighted to toggle it up or down)
Left: UP
Down: UP
Up: DOWN
Right: DOWN

With this new system, it is possible to reverse 1 or 3 columns at a time, and not have it break on other game modes. There is no guesswork with the 50% and -50% Alternate, Cross, Split required before.

Are old courses still supported in 5.1?
