### ISSUE TITLE
Some things I am wondering about the special days feature/easter eggs

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#16]
I think there needs to be an option to add custom special days in the next release.
 
Like for my birthday I could make the default mode 3 panel instead of single, and force flip, -100% invert to be on for every other mode except 3 panel (in 3 panel it is broken so that is the only mode that will stay intact).

Also are the numbers wrong in the script for special days? Did April Fools day change to March 1? Because it says 3 for the month. And is your birthday (the day only double charts can be played) October 7?

**Comment by kyzentun** [comment]
I don't want to spend time creating a generalized system for special days with a variety of behaviors.  It doesn't seem useful enough to be worth the trouble, and impossible to really solve generally.  Everybody would be picking stuff outside of the existing list of possible behavior, so it would just grow into a clumsy mess that causes weird problems.

The numbers for the month aren't wrong in my script.  The ancient C functions that stepmania uses internally to get the current month return 0-11.  So 3 is April.

**Comment by 1033Forest** [comment]
Oh... so to choose a month, the number is 1 less than the actual number for the month.
Like this:
0 = January
1 = February
2 = March
all the way to
11 = December

**Comment by 1033Forest** [comment]
Other ideas for special days (based on real life holidays, these may or may not be implemented)

New year: Instead of "Consensual" on the title screen, it will show what the current year is, and force confetti to always be on
Valentines day: Give the theme a Simply Love-like look
St. Paddy's day: Make the theme green
Easter: Cannot be implemented because Easter can fall on different days in different years
Independence day: Replace the circles with stars, and put fireworks in the background
Halloween: Change main theme colors to black, orange, and purple, also make the sounds spooky
Thanksgiving: Also cannot be implemented
Christmas: Make the theme red, and force a special confetti (snow) to be on, and receptor warnings can alternate red and green
