### ISSUE TITLE
Cannot escape song modifier menu in edit mode

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#17]
I want to change the noteskin, or add a modifer, so I go to the edit menu, and select my modifiers. When I select "Play Song" or exit out of the modifier menu it gives me an error "Error running input callback", which makes me stuck in the modifier menu and forces me to restart.

**Comment by kyzentun** [comment]
Should be possible to get out of the menu now.  You'll have to use the shortcuts shown in the upper left to change the speed mod.
