### ISSUE TITLE
SM assistant?

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#18]
Just one of my weird ideas. This can be turned on or off in the options menu.
An annoying assistant (like Clippy) pops up on the bottom right of the screen. It would look like a up right diagonal arrow with 2 eyes. When starting a song it would say something like "It looks like you're trying to start playing. Do you want help?". Then if say no, will jump straight into the game. It can sometimes bug you while playing "It looks like you're trying to hit a ______" (fill in the blank with whatever pattern). It could also comment on results on the evaluation screen.

A weird and not very good idea, but what do you think of it?

**Comment by kyzentun** [comment]
More work than it's worth.  It'd be amusing for 30 seconds then irritating.
