### ISSUE TITLE
Negative speed mods

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#20]
I found out, on this theme it is actually possible to have negative speed mods, which make the arrows go the other way.

In standard scroll, the notes come from the top of the screen
In reverse, the notes come from the bottom

Should this feature still be there, or should it be removed? Because it seems very interesting, please dont remove it..

And if using a negative speed mod the hold ends (top or bottomcaps) aren't rendered.

**Comment by kyzentun** [comment]
Not a bug.
