### ISSUE TITLE
Black screen when minimizing

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#21]
When I minimize and bring it back up, it shows a black screen. It is still playable but I see nothing on the screen.

I haven't tested on other themes, this so far only happens on Consensual, that's why I'm putting it here now.

**Comment by kyzentun** [comment]
Probably an engine bug, not a theme bug.

**Comment by 1033Forest** [comment]
The bug doesn't happen in other themes. Only this one.
And if I try to bring the window back up during a demonstration it crashes.

**Comment by 1033Forest** [comment]
StepMania5.1-git-767999d crash report (build 767999d, 20160623 @ 05:58:43)
--------------------------------------

Crash reason: 1286

Thread: Main thread
        GraphicsWindow.cpp:55 Msg 20, wParam e8010e94, lParam 00000000
        GraphicsWindow.cpp:180 Msg 20, wParam e8010e94, lParam 00000000
        GraphicsWindow.cpp:180 Msg 15, wParam 00000000, lParam 00000000
        ScreenGameplay.cpp:2721 HandleScreenMessage(SM_DoneFadingIn)
        RageDisplay_OGL.cpp:1459 1286
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:788 
        InputHandler_DirectInput.cpp:759 
        InputHandler_DirectInput.cpp:783 
        InputHandler_DirectInput.cpp:788 
        InputHandler_DirectInput.cpp:759 
Thread: Streaming sound buffering
00f551e8: StepMania!00a90000
00b5002d: StepMania!00a90000
00e350f5: StepMania!00a90000
00e3529b: StepMania!00a90000
00c2e4b1: StepMania!00a90000
00e2f189: StepMania!00a90000
00c331e0: StepMania!00a90000
1005dd84: ig4icd32!10000000
1023350b: ig4icd32!10000000
00c2e841: StepMania!00a90000
00c03090: StepMania!00a90000
00c0309b: StepMania!00a90000
00c03823: StepMania!00a90000
00c0f8f1: StepMania!00a90000
00c03823: StepMania!00a90000
00c6c0bb: StepMania!00a90000
102555ad: ig4icd32!10000000
1025565a: ig4icd32!10000000
00c11c83: StepMania!00a90000
00c68365: StepMania!00a90000
00e56788: StepMania!00a90000
00c61adb: StepMania!00a90000
00c03823: StepMania!00a90000
00c66296: StepMania!00a90000
00c663dc: StepMania!00a90000
00c61a65: StepMania!00a90000
00c03823: StepMania!00a90000
00c68405: StepMania!00a90000
00c82c5b: StepMania!00a90000
00c03823: StepMania!00a90000
00c03870: StepMania!00a90000
00c038d6: StepMania!00a90000
00c0f8f1: StepMania!00a90000
00c03823: StepMania!00a90000
00bd1ddc: StepMania!00a90000
00b4ef84: StepMania!00a90000
00b59b45: StepMania!00a90000
01016647: StepMania!00a90000
0101663e: StepMania!00a90000
00f54d66: StepMania!00a90000
0101f517: StepMania!00a90000
77bd98d5: ntdll!RtlInitializeExceptionChain [77ba0000+3989f+36]

Static log:
StepMania5.1-git-767999d
Compiled 20160623 @ 05:58:43 (build 767999d)
Log starting 2016-06-25 20:05:47
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 4060mb total, 4095mb swap (2704mb swap avail)
Video driver: Intel(R) G45/G43 Express Chipset [Intel Corporation]
              8.15.10.1840, 7-3-2009 [pci\ven_8086&dev_2e22]
WARNING: RegOpenKeyEx(%p,%s) error (The system cannot find the file specified.)
Sound device 0: Speakers (High Definition Audio, 0.0, MID 1, PID 65535 
WARNING: Error loading noteskin '/NewSkins/babykai/noteskin.lua': /NewSkins/babykai/noteskin.lua:1: unexpected symbol near 'ï'
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
WARNING: Video renderer list has been changed from 'd3d,opengl' to 'opengl'
Video renderers: 'opengl'
Mode: ICD 32 (888) 8 alpha 16 depth 64 accum 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: Intel
OGL Renderer: Intel(R) G45/G43 Express Chipset
OGL Version: 2.1.0 - Build 8.15.10.1840
OGL Max texture size: 4096
OGL Texture units: 8
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_3DFX_texture_compression_FXT1
  GL_ARB: color_buffer_float, depth_texture, draw_buffers, fragment_program, fragment_shader, half_float_pixel, 
    multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, shader_objects, 
    shading_language_100, shadow, texture_border_clamp, texture_compression, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_non_power_of_two, 
    texture_rectangle, transpose_matrix, vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI_separate_stencil
  GL_EXT: abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, blend_subtract, 
    clip_volume_hint, compiled_vertex_array, draw_range_elements, fog_coord, framebuffer_object, 
    multi_draw_arrays, packed_pixels, rescale_normal, secondary_color, separate_specular_color, shadow_funcs, 
    stencil_two_side, stencil_wrap, texture3D, texture_compression_s3tc, texture_env_add, texture_env_combine, 
    texture_filter_anisotropic, texture_lod_bias, texture_rectangle, texture_sRGB, texture_swizzle
  GL_IBM_texture_mirrored_repeat
  GL_NV: blend_square, conditional_render, texgen_reflection
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
  GL_WIN_swap_hint
OpenGL Windowed 854x480 16 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 3 (buffered)
WARNING: Startup time: 56.88399887085
Players joined: P1, P2
Lost focus to: (NULL), chrome.exe
Top Screen: ScreenDemonstration
Language: en
Current renderer: OpenGL
Theme: consensual-master

Partial log:
02:17.733: Loaded "ScreenDemonstration" ("ScreenDemonstration") in 13.062000
02:17.733: Loading screen background "/Themes/_fallback/BGAnimations/ScreenGameplay background.lua"
02:17.764: PushScreen: "ScreenDemonstration"
02:17.768: Performing texture garbage collection.
02:17.777: Zeroing this update.  Was 13.123000
02:17.824: Approximate sound time: driver frame 5944052, m_pImpl->m_Queue frame 0..2048 (dist 5388), closest position is 0
02:18.779: 59 FPS, 59 av FPS, 1444 VPF, OpenGL
02:19.789: 64 FPS, 61 av FPS, 1466 VPF, OpenGL
02:20.841: 56 FPS, 58 av FPS, 1306 VPF, OpenGL
02:21.867: 42 FPS, 55 av FPS, 1306 VPF, OpenGL

-- End of report

**Comment by 1033Forest** [comment]
Only happens on this theme, and not others like default: If I try to minimize everything in the window turns black forcing me to restart.
