### ISSUE TITLE
Giant graph looking thing at the top of the evaluation screen

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#22]
Why is there a giant graph looking thing on the top of the screen? When I play with autoplay, only the cyan part of it is graphed, and the other colors are a straight line. I noticed it when I updated my theme. How do I get rid of it?

**Comment by 1033Forest** [comment]
http://i.imgur.com/5veJnaN.png

Before I updated stepmania, I did not see this giant graph on the top. For me, this giant graph thingy or whatever it's called, it takes up too much space and blocks the pad icons. That's why I want to get rid of it.

**Comment by kyzentun** [comment]
I'm surprised it took two weeks for you to notice it.  It shouldn't be hard to figure out what it is if you look at the numbers and colors.

**Comment by 1033Forest** [comment]
The numbers are too small, but the colors I know represent the different judgements.
I didn't see this until I updated the theme with the update that lets me exit the modifier menu in edit mode. Then it just kept appearing on the evaluation screen.

What I'm trying to figure out now is how to get rid of it, since it's blocking the pad icons on the evaluation screen.

**Comment by 1033Forest** [comment]
I really need to know how to get rid of it. I can't find any option in the theme prefs to get rid of that giant graph thing or whatever it's called from the evaluation screen. It's been bothering me a lot since I updated the theme with the update that lets you exit the editor menu. I didn't see that before I updated the theme, and when I updated it it just appeared.

**Comment by kyzentun** [comment]
I don't feel like putting options in for it, so I'm just removing it for now.  Obviously I'd have to size the text better to make it usable as an actual feature.

**Comment by 1033Forest** [comment]
Thanks that got rid of it.
