### ISSUE TITLE
(Not a bug, just a question) 100% is distorted

### ISSUE THREAD

**Issue by 1033Forest** [kyzentun/consensual#24]
If I get a 100% on a song, when I go back to select it in the select music screen, the 100% appears distorted. Why is that?

And is the highest grade the only one to be cyan?

**Comment by kyzentun** [comment]
1.  Not a bug.

2.  That's the way the grading coloration works.

**Comment by 1033Forest** [comment]
I had some fun with the distorted 100%, by alternating left and right on that song and "Previous Song". It looked like it was waving, or water.
