### ISSUE TITLE
WHAT THE HELL?!

### ISSUE THREAD

**Issue by powie444** [kyzentun/consensual#25]
I CAN'T COMPILE STEPMANIA 5.1.-3 BECAUSE I DON'T KNOW HOW!!!

SOMEONE PLEASE GIVE ME STEPMANIA 5.1.-3! )':

**Comment by powie444** [comment]
THIS THEME IS A STUPID WASTE OF TIME FOR ME! **I GIVE UP!**

**Comment by kyzentun** [comment]
Hahaha, sorry, there's a link to the last version that supports 5.0.11 in the readme.  It should show it on screen when you try to run too.

**Comment by powie444** [comment]
NO. I WANT TO USE THE 5.1.-3 VERSION, BUT I CAN'T **COMPILE** STEPMANIA 5.1.-3!

# **THANK YOU FOR NOT HELPING!!! ):<**

**Comment by powie444** [comment]
# **I'M NOT KIDDING!**

**Comment by powie444** [comment]
How I Feel Righ Now: [https://youtu.be/QSPoQ0nEa0I?t=3m14s](url)

**Comment by kyzentun** [comment]
I don't have a reliable way to make builds for windows or OS X, so there's not much I can do about it.

**Comment by powie444** [comment]
Well Then...
# I'M GOING TO KILL YOU!
### THEN IT'S OFF TO VISIT YOUR MOM!
_TF2 Joke/Reference/Something._

**Comment by 1033Forest** [comment]
Install Visual Studio 2015
Use cmake to generate a project file
Open the project file in visual studio then build
