### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by whatsthepoint** [kyzentun/consensual#26]
![untitled](https://cloud.githubusercontent.com/assets/12676311/17564078/3503097c-5f00-11e6-9af4-75f63c9d92d0.png)
I guess I never noticed it before because I'm usually in fullscreen mode. This is for the 5.0 version so if it's not an issue for master then just close.

**Comment by kyzentun** [comment]
Did you reload overlay screens?  I've only seen this happen when using the debug menu to reload overlay screens.

**Comment by whatsthepoint** [comment]
I'm not really sure what I did. I was just going through the SM settings screens and then I changed themes around and it popped up and I clicked ignore and moved on.

**Comment by whatsthepoint** [comment]
Oh, I figured out how to get this error now.

1. Be in windowed mode (which I'm usually not in).
2. Change the resolution.

This is with 5.1.-3 on Windows using consensual from master. I don't notice anything actually not working apart from the error popping up though.

**Comment by kyzentun** [comment]
Should be fixed.
https://github.com/kyzentun/consensual/commit/4ae9ba4affe5a433fb7af63279479e7d040d2bd7
