### ISSUE TITLE
Mine options, roll options?

### ISSUE THREAD

**Issue by vegeta897** [kyzentun/consensual#5]
I like to play with mines and rolls disabled (mines are removed, rolls are converted into holds). I can easily set these options in the default Stepmania theme, but I can't figure out where to set these options in this theme. Is it possible?

**Comment by kyzentun** [comment]
Set your Options Level to at least 2, then go to the "Chart Mods", then to "No".  That has all the mods for removing things from the chart.  Hit "Set Persistent" after turning on the ones you want to make it permanent for your profile.

**Comment by vegeta897** [comment]
Thanks for the quick response, I totally missed that menu.

No mines works great, but I can't seem to convert rolls to holds. Selecting HoldRolls in the No menu converts all holds to rolls, which is the opposite of what I'm looking for.

**Comment by kyzentun** [comment]
Looks like I somehow missed that function when putting everything in the mods menu.  It's in there now.
https://github.com/kyzentun/consensual/commit/47980e1a537b6c0aee95a455d333171905ba1d31
