### ISSUE TITLE
Mini 50% as a default mod

### ISSUE THREAD

**Issue by SoonDead** [kyzentun/consensual#6]
How do I set Mini 50% automatically upon loading the game? Is it possible?

Cannot figure out how to. Too many options.

![mind exploded](http://i.imgur.com/s8JlpMN.gif)

**Comment by kyzentun** [comment]
Use the persistent mods feature.  Which I haven't ported to 5.1 yet.  I also need to reorganize the mods menu a lot.
http://i.imgur.com/S67DTeu.png

**Comment by SoonDead** [comment]
Set persistent (while present under a lot of options) seemed to have been missing from floaty mods a few hours ago. I have no idea what changed. I might have created a player profile since then. Or it was present I just completely missed it.

Also I don't know how to put it lightly but **HOLY TREECOCKS** this theme is insane. In a good way.

**Comment by kyzentun** [comment]
The persistent mods stuff only shows up when you have a profile to save it to.  For SM 5.1, I'm going to be moving mini and perspective mods to a general NoteField Config menu: http://i.imgur.com/LgfZn2x.jpg
(Select Music, Player Options, and Gameplay are going to share large chunks of menu code too)
