### ISSUE TITLE
Selecting profile menu option with no profile

### ISSUE THREAD

**Issue by whatsthepoint** [kyzentun/consensual#7]
Selecting the profile menu option while not having any profiles leads to erroneous indexing. I came across this while setting up a fresh StepMania.
```
WARNING: Error running input callback: /Themes/consensual/Other/options_menu.lua:507: attempt to index a nil value
WARNING: /Themes/consensual/Other/options_menu.lua:507: unknown(self = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = 1,(*temporary) = attempt to index a nil value)
WARNING: (tail call): tail((*temporary) = (null),(*temporary) = (null))
WARNING: /Themes/consensual/BGAnimations/ScreenInitialMenu overlay.lua:460: interpret_code(pn = PlayerNumber_P1,code = MenuDown,current_menu = (null))
WARNING: /Themes/consensual/BGAnimations/ScreenInitialMenu overlay.lua:604: unknown(event = (null))
```

**Comment by whatsthepoint** [comment]
Actually, for me, I guess using the profile menu in general leads to that error and then I'm stuck on the menu screen. This is using a fresh clone of consensual on the 5.0.9 Linux binaries from the release page. Am I supposed to be using 5.1.0 or head instead?

**Comment by kyzentun** [comment]
Try 5.0.10.  Do not try the October alpha release of 5.1.0, because I've updated the 5.1 related code to use stuff that isn't in that release.

5.0.9 should work, I'll have to investigate this problem.

**Comment by whatsthepoint** [comment]
Er, I goofed. I'm actually already on 5.0.10. That was a typo because I thought it was the latest pre-5.1.0 number.

```
StepMania5.0-git-108b297
Compiled 20151030 @ 23:06:04 (build 108b297)
```

**Comment by kyzentun** [comment]
So I just tried running with my ~/.stepmania-5.0/Save folder completely cleared, and I was able to use the profile menu just fine.  Can you send me the log file so I can see if other things went wrong?

**Comment by whatsthepoint** [comment]
Sent to the Gmail address on your GitHub profile.

**Comment by kyzentun** [comment]
I can't find a problem, so pull the latest commit which should give me some more debugging info and try it.

**Comment by kyzentun** [comment]
Ah, so this only happens when you move one player's cursor down the menu, which puts the other player's cursor in the non-visible area?

**Comment by kyzentun** [comment]
Should be fixed now.

**Comment by whatsthepoint** [comment]
Yes, it works now.
