### ISSUE TITLE
Display +/-favorite on results screen and keybindings for +/- favorite?

### ISSUE THREAD

**Issue by OwenDurni** [kyzentun/consensual#8]
Wondering if it would be possible to have +/- favorite display on the results screen under profile and to have the option to bind specific keys to increase and decrease the favorite rating.

I tend to like to play on random and this would help me start to curate my collection without needing to menu back to recently played to adjust the favorite score of a song. (I know you can menu on the results screen to +/- favorite but the current value is not displayed so it is hard to tell if I've already adjusted a song).

(P.S. Thanks for making this theme!)

**Comment by kyzentun** [comment]
There's actually already a menu on eval, hit Select to bring it up.  I need to make the value visible though.

The main reason I haven't added special bindings for stuff is that ideally, everything in the game should be doable from a dance pad.  Also, stepmania already has too many keys to bind.

**Comment by OwenDurni** [comment]
Not adding a key binding is a perfectly reasonable design decision (if you add one for this you'll get asked to add one for "everything").
