### ISSUE TITLE
Option to toggle elapsed time/song time and song title in gameplay

### ISSUE THREAD

**Issue by lostonroute66** [kyzentun/consensual#9]
Would be nice to have an option to toggle all the decorations off in gameplay mode, so you only see the steps/top arrows and background image/video.

Thanks for the outstanding theme!

**Comment by kyzentun** [comment]
Done.  https://github.com/kyzentun/consensual/commit/561ffc74740c417f35a29ca564c17e4ab2ee1907
Note that current Consensual only supports StepMania 5.1.-3, which isn't out yet.  So it won't work if you're not running the 5_1_0 branch of StepMania.
